In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/wafer.csv')

In [4]:
df.head()

,Unnamed: 0,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,Wafer-801,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,Wafer-802,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,Wafer-803,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1
3,Wafer-804,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1
4,Wafer-805,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1

In [5]:
df.drop(columns='Unnamed: 0',inplace=True)

In [6]:
df.drop(columns='Good/Bad', inplace=True)

In [7]:
def check_std(df : pd.DataFrame):
    drop_col = []
    num_cols = [col for col in df.columns if df[col].dtype != 'O']
    for col in num_cols:
        if df[col].std() == 0:
            drop_col.append(col)
    return drop_col

In [8]:
def check_null(df: pd.DataFrame , thresold = .7):
    cols_missing_ratios = df.isna().sum().div(df.shape[0])
    cols_to_drop = list(cols_missing_ratios[cols_missing_ratios > thresold].index)
    return cols_to_drop

In [11]:
cols_drop_null = check_null(df,thresold=.7)
cols_drop_std = check_std(df)
drop_cols  = cols_drop_std + cols_drop_null

In [12]:
df.drop(columns=drop_cols,inplace=True)

In [13]:
df.to_csv('input__.csv',index=False)